"""empty message

Revision ID: b8934f827985
Revises: 
Create Date: 2020-01-02 14:51:21.074066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8934f827985'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home', sa.Integer(), nullable=False),
    sa.Column('away', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_projection', sa.Float(), nullable=True),
    sa.Column('away_projection', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id', 'date', 'home', 'away')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('team')
    # ### end Alembic commands ###
